fixing ci

diff --git a/testCoverage b/testCoverage
--- a/testCoverage
+++ b/testCoverage
@@ -1,14 +1,24 @@
 #!/bin/bash
+
 EXITCODE=0;
 WATERMARK=$2;
-COVEROUTPUT=`godep go test -cover $1`;
-echo ${COVEROUTPUT};
+TESTDIR=$1
+godep go test -cover ${TESTDIR} | {
+  while read -r COVEROUTPUT;do 
+    echo ${COVEROUTPUT};
 
-COVERLEVELS=`echo ${COVEROUTPUT} | grep -oh "[0-9]\{1,3\}\.[0-9]\{1,3\}\%"`
-for COVERLEVEL in ${COVERLEVELS};do
-    echo ${COVERLEVEL} | tr "%" " ";
-    COVERLEVEL=${COVERLEVEL/.*};
-    echo "Coverage - ${COVERLEVEL}%";
-    echo "Watermark- ${WATERMARK}%";
-    if (( $COVERLEVEL < $WATERMARK )); then echo "failed"; (exit 1); fi
-done
+    COVERLEVELS=`echo ${COVEROUTPUT} | grep -oh "[0-9]\{1,3\}\.[0-9]\{1,3\}\%"`
+    for COVERLEVEL in ${COVERLEVELS};do
+        echo ${COVERLEVEL} | tr "%" " ";
+        COVERLEVEL=${COVERLEVEL/.*};
+        echo "Coverage - ${COVERLEVEL}%";
+        echo "Watermark- ${WATERMARK}%";
+        if [[ $COVERLEVEL -lt $WATERMARK ]]; then echo "!!!!    FAIL    !!!!"; EXITCODE=1;fi
+    done
+    EXITCODE=$EXITCODE
+  done
+  exit ${EXITCODE}
+}
+
+
+
